kind: Deployment
apiVersion: apps/v1
metadata:
  name: dep1
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      role: myapp
  template:
    metadata:
      labels:
        role: myapp
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
        - name: cont1
          image: lerndevops/ctapp:v2
          ports:
            - name: http
              containerPort: 8080

